name: integrate-lighthouse-script

# preview builds triggered on PRs into the <ui-perf-shootout> branch
on: [pull_request]

jobs:
  lighthouse-audit-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run:  mkdir ${{ github.workspace }}/lightHouseResults
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        urls: 'https://www.espn.com'
    - name: Upload report
      uses: actions/upload-artifact@master
      with:
        name: Lightout report output
        # specify directory/filePath we want to write to
        path: ${{ github.workspace }}/lightHouseResults
