name: integrate-lighthouse-script

# preview builds triggered on PRs into the <ui-perf-shootout> branch
on: [pull_request]

jobs:
  lighthouse-audit-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://www.espn.com'
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: Lightout report output
        # specify directory/filePath we want to write to
        path: lightHouseResults/test.txt

