name: integrate-lighthouse-script

# preview builds triggered on PRs into the <ui-perf-shootout> branch
on: [pull_request]

jobs:
  lighthouse-audit-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: "www.espn.com"
    - name: Upload report
      uses: 
      with:
        name: Lightout report output
        path: ../

