name: integrate-lighthouse-script

# preview builds triggered on PRs into the <ui-perf-shootout> branch
on: [pull_request]

jobs:
  lighthouse-audit-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run:  mkdir ${{ github.workspace }}/lightHouseResults
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        # here we'll use the access tokens from a different GH account to output to PRs
        accesstoken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN}}
        outputDirectory: ${{ github.workspace }}/lightHouseResults
        urls: 'https://www.espn.com'
    # artifacts upload that wipes on new merges (actions runs in containera)
    - name: Upload report
      uses: actions/upload-artifact@master
      with:
        name: Lightout report output
        path: ${{ github.workspace }}/lightHouseResults
        